const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),Module=require('node:module'),ts=require('typescript'),React=require('react');
const {renderToStaticMarkup}=require('react-dom/server');
function load(file,stubs={}){const m=new Module(__filename,module);m.paths=module.paths;m.require=id=>Object.hasOwn(stubs,id)?stubs[id]:require(id);m._compile(ts.transpileModule(fs.readFileSync(require.resolve(file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,__filename);return m.exports;}
const pricing=load('../lib/tire-shop-pricing.ts'),stock=load('../lib/tire-stock-filter.ts');
const Card=load('../components/StaffTireCard.tsx',{'@/lib/tire-shop-pricing':pricing,'@/lib/tire-stock-filter':stock,'./StaffTireCard.module.css':{__esModule:true,default:new Proxy({},{get:(_,key)=>String(key)})}}).default;
const tire={id:'usaf-1',supplier:'USAF',brand:'NITTO',model:'Terra Grappler G3',size:'275/55R20',description:'Tire',loadSpeed:'117 T',loadRange:'XL',warranty:'70000',category:'All-terrain',snowRated:true,cost:220.99,fet:0,map:302,suggestedPrice:281,quotePrice:302,installedPrice:370,estimatedTotals:{2:800,4:1595},imageUrl:'https://example.com/tire.jpg',atdProductNumber:'224060',manufacturerProductNumber:'224060',fitmentPosition:'both',availability:{local:0,localPlus:9,nationwide:9},runFlat:false,discontinued:false,treadDepth:'13',utqg:'600',sidewall:'BSW',oeMarking:''};
const atd={...tire,id:'atd-1',supplier:'ATD',cost:228.5,availability:{local:8,localPlus:69,nationwide:80}};
const props={tire,offers:[tire,atd,{...tire,id:'ntw',supplier:'NTW',cost:undefined}],price:'302.00',quantity:4,staggered:false,selected:false,quoteFull:false,imageFailed:false,onImageFailed(){},onImage(){},onSupplier(){},onPrice(){},onQuantity(){},onQuote(){},onOrder(){},onDetails(){},onWarehouses(){},warehouses:[],warehouseLoading:false,warehouseError:''};
function walk(node,predicate,found=[]){if(!node||typeof node!=='object')return found;if(Array.isArray(node)){node.forEach(n=>walk(n,predicate,found));return found;}if(predicate(node))found.push(node);walk(node.props?.children,predicate,found);return found;}
test('supplier cards and selected totals include FET, and profit subtracts the combined cost only once',()=>{
  const offer={...atd,...pricing.supplierCostBreakdown(309,32.14),quotePrice:387};
  const html=renderToStaticMarkup(React.createElement(Card,{...props,tire:offer,offers:[offer],price:'387'}));
  for(const text of ['$341.14','Base $309.00 + FET $32.14 / tire','Cost incl. FET / tire','$45.86','Your cost for 4: $1,364.56'])assert(html.includes(text),text);
  const missing=renderToStaticMarkup(React.createElement(Card,{...props,tire:{...offer,fet:null},offers:[{...offer,fet:null}]}));
  assert(missing.includes('FET not provided'));assert(missing.includes('Confirm FET first'));assert(!missing.includes('$45.86'));
});
test('staff F1 renders photo, each priced supplier, availability, MAP and selling price',()=>{const html=renderToStaticMarkup(React.createElement(Card,props));for(const text of ['Enlarge NITTO','U.S. AutoForce','ATD','$220.99','$228.50','8 local','69','Supplier MAP / tire','$302.00','Our price / tire','$81.01','$1,208.00','$1,595.00'])assert.ok(html.includes(text),text);assert(!html.includes('NTW'));assert(html.includes('Not provided')===false);});
test('missing costs, invalid MAP and no inventory do not fabricate prices or allow ordering',()=>{for(const cost of [undefined,null,0,-1,NaN,Infinity])assert.equal(pricing.hasSupplierCost({cost}),false);const html=renderToStaticMarkup(React.createElement(Card,{...props,tire:{...tire,cost:undefined,map:0,availability:{local:0,localPlus:0,nationwide:0}},offers:[]}));assert.match(html,/Not provided/);assert.match(html,/No supplier pricing available/);assert.match(html,/disabled=""[^>]*>Out of stock/);});
test('supplier, price, MAP, quantity, photo, quote and order callbacks target current controls',()=>{let chosen,price,quantity,photo=false,quote=false,order=false;const tree=Card({...props,onSupplier:x=>chosen=x,onPrice:x=>price=x,onQuantity:x=>quantity=x,onImage:()=>photo=true,onQuote:()=>quote=true,onOrder:()=>order=true});const nodes=walk(tree,n=>typeof n.type==='string');nodes.find(n=>n.type==='button'&&n.props['aria-pressed']===false&&n.props.className==='supplier').props.onClick();assert.equal(chosen.id,'atd-1');nodes.find(n=>n.type==='input').props.onChange({target:{value:'290'}});assert.equal(price,'290');nodes.find(n=>n.props.className==='useMap').props.onClick();assert.equal(price,'302.00');nodes.find(n=>n.type==='select').props.onChange({target:{value:'2'}});assert.equal(quantity,2);nodes.find(n=>n.props.className==='photo').props.onClick();assert(photo);const actions=nodes.find(n=>n.props.className==='actions');actions.props.children[0].props.onClick();actions.props.children[1].props.onClick();assert(quote&&order);});
test('price override preserves fees at each quantity, cost, MAP and source data',()=>{const changed=pricing.withQuotePrice(atd,290);assert.equal(changed.quotePrice,290);assert.equal(changed.estimatedTotals['4'],1547);assert.equal(changed.estimatedTotals['2'],776);assert.equal(changed.cost,228.5);assert.equal(changed.map,302);assert.equal(atd.quotePrice,302);assert.equal(pricing.withQuotePrice(tire,NaN),tire);assert.equal(pricing.withQuotePrice(tire,-1),tire);});
test('selected supplier drives cost, profit and invalid price disables adding',()=>{const html=renderToStaticMarkup(React.createElement(Card,{...props,tire:pricing.withQuotePrice(atd,290),price:'290.00'}));assert(html.includes('$61.50'));assert(html.includes('Our price is below MAP'));const invalid=renderToStaticMarkup(React.createElement(Card,{...props,price:''}));assert.match(invalid,/Enter a valid selling price/);assert.match(invalid,/disabled=""[^>]*aria-pressed="false"/);});
test('staff integration is isolated from public cards and session preserves overrides',()=>{const source=fs.readFileSync(require.resolve('../components/TireShoppingBeta.tsx'),'utf8');assert.match(source,/if \(internal\) \{[\s\S]*return <StaffTireCard/);assert.match(source,/showOutOfStock, staffDrafts/);assert.match(source,/setStaffDrafts\(saved.staffDrafts \|\| \{\}\)/);assert.match(source,/setOrderQuantity\(count\); setUsafOrderProduct\(display\)/);assert.match(source,/Customize & buy/);const css=fs.readFileSync(require.resolve('../components/StaffTireCard.module.css'),'utf8');assert(css.includes('@media(max-width:800px)'));assert(!css.includes('.tire-beta-product'));});
