import { DashboardStats, Job } from './types';

export const demoJobs: Job[] = [
  {
    id: '1',
    created_at: '2026-04-02T08:00:00.000Z',
    customer_name: 'DIETZ',
    tire: 'COOPER WB',
    tire_size: '385/65R22.5',
    quantity: 2,
    ordered: true,
    vehicle: 'KENWORTH',
    position: 'FRONTS',
    scheduled: true,
    scheduled_at: '2026-04-03T12:00:00.000Z',
    contact_name: 'DOMINIC',
    phone: '8453992633',
    address: '474 SPRINGTOWN RD, NEW PALTZ, NY',
    email: null,
    total: null,
    billed: false,
    paid: false,
    complete: true,
    notes: null,
  },
  {
    id: '2',
    created_at: '2026-04-05T08:00:00.000Z',
    customer_name: 'TREVOR KRANEC',
    tire: 'PIRELLI PZERO',
    tire_size: '285/35R22;315/30R22',
    quantity: 4,
    ordered: true,
    vehicle: 'PORSCHE CAYENNE',
    position: 'ALL',
    scheduled: true,
    scheduled_at: '2026-04-06T15:00:00.000Z',
    contact_name: 'TREVOR',
    phone: '(908) 892-1284',
    address: '350 CRANS MILL RD',
    email: 'ashleyafagan87@gmail.com',
    total: 2985,
    billed: false,
    paid: false,
    complete: false,
    notes: null,
  },
  {
    id: '3',
    created_at: '2026-04-01T08:00:00.000Z',
    customer_name: 'MIKE MCCONNEL',
    tire: 'Hankook Kinergy',
    tire_size: '235/40R19',
    quantity: 1,
    ordered: true,
    vehicle: 'NISSAN ALTIMA',
    position: 'NA',
    scheduled: true,
    scheduled_at: '2026-04-10T15:00:00.000Z',
    contact_name: 'MIKE',
    phone: '(845) 427-1921',
    address: 'SOUTH NEIGHBOR',
    email: null,
    total: 440,
    billed: false,
    paid: false,
    complete: false,
    notes: 'Swap in summer tires',
  },
  {
    id: '4',
    created_at: '2026-04-05T08:00:00.000Z',
    customer_name: 'BRIAN HOWARD',
    tire: 'IRONMAN ALL COUNTRY HT 4S',
    tire_size: '235/70R16 106T',
    quantity: 2,
    ordered: true,
    vehicle: null,
    position: null,
    scheduled: false,
    scheduled_at: null,
    contact_name: null,
    phone: null,
    address: null,
    email: null,
    total: null,
    billed: false,
    paid: false,
    complete: false,
    notes: null,
  },
];

export const demoStats: DashboardStats = {
  dueToday: 0,
  dueThisWeek: 2,
  unscheduled: 1,
  unpaid: 2,
};
