create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  quote_number bigint generated by default as identity unique,
  status text not null default 'draft' check (status in ('draft','sent','viewed','approved','declined','expired','converted')),
  customer text not null,
  contact_name text,
  phone text,
  email text,
  vehicle text,
  tire_size text,
  quantity integer not null default 4,
  address text,
  notes text,
  service_category text not null default 'passenger' check (service_category in ('passenger','truck','commercial')),
  installation_cost numeric(12,2) not null default 0,
  service_call_fee numeric(12,2) not null default 0,
  disposal_fee numeric(12,2) not null default 0,
  ny_state_tire_fee numeric(12,2) not null default 0,
  sales_tax_rate numeric(8,4) not null default 0,
  tax_exempt boolean not null default false,
  selected_option_id uuid,
  expires_at date,
  converted_job_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quote_options (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  tier text not null check (tier in ('good','better','best')),
  brand text not null,
  model text not null,
  image_url text,
  price_per_tire numeric(12,2) not null default 0,
  warranty_miles integer,
  tire_type text,
  load_speed_rating text,
  snow_rating text,
  highlights text,
  availability text,
  recommended boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (quote_id, tier)
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'quotes_selected_option_fk'
  ) then
    alter table public.quotes
      add constraint quotes_selected_option_fk
      foreign key (selected_option_id) references public.quote_options(id) on delete set null;
  end if;
end $$;

create index if not exists quotes_status_created_idx on public.quotes (status, created_at desc);
create index if not exists quotes_customer_idx on public.quotes (customer);
create index if not exists quote_options_quote_idx on public.quote_options (quote_id, sort_order);

alter table public.quotes enable row level security;
alter table public.quote_options enable row level security;

create policy "Allow authenticated read quotes" on public.quotes for select using (auth.role() = 'authenticated');
create policy "Allow authenticated insert quotes" on public.quotes for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated update quotes" on public.quotes for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Allow authenticated delete quotes" on public.quotes for delete using (auth.role() = 'authenticated');

create policy "Allow authenticated read quote options" on public.quote_options for select using (auth.role() = 'authenticated');
create policy "Allow authenticated insert quote options" on public.quote_options for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated update quote options" on public.quote_options for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Allow authenticated delete quote options" on public.quote_options for delete using (auth.role() = 'authenticated');
