create table if not exists public.kingdom_facilities (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (name, address)
);

alter table public.kingdom_facilities enable row level security;

alter table public.customer_orders
  add column if not exists facility_id bigint references public.kingdom_facilities(id),
  add column if not exists facility_name text;

alter table public.jobs
  add column if not exists facility_id bigint references public.kingdom_facilities(id),
  add column if not exists facility_name text;

